id: P009387
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS17566
  title: སྙན་ངག་མེ་ལོང་གི་དཀའ་འགྲེལ།
  author: ''
  volumes:
    23c29a5baf044bcb9686555e466454d5:
      image_group_id: I8LS17576
      title: ''
      volume_number: 1
      total_pages: 350
      base_file: v001.txt
