id: I040D0A4A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T08:59:43+00:00'
last_modified: '2022-06-08T10:39:10.655321+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17566
  title: སྙན་ངག་མེ་ལོང་གི་དཀའ་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8A18:
      image_group_id: I8LS17576
      title: ''
      total_pages: 350
      order: 1
      base_file: 8A18.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
